version: '3.8'

services:
  postgres:
    container_name: python-task-management-api-postgres
    image: postgres:15
    environment:
      POSTGRES_DB: task_management
      POSTGRES_USER: task_api_user
      POSTGRES_PASSWORD: task_api_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"  # Mapped to 5433 to avoid conflicts with any local PostgreSQL
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      # - ./init-scripts:/docker-entrypoint-initdb.d  # Optional: for initialization scripts
    networks:
      - python-task-management-api-network
    restart: unless-stopped

networks:
  python-task-management-api-network:
    name: python-task-management-api-network
    driver: bridge