[project]
name = "task-management-api"
version = "0.1.0"
description = "a simple task management api created using fastapi"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi==0.115.8",
    "ruff==0.9.7",
    "uvicorn==0.34.0",
]
